version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 14
        commands:
            - chmod +x src/local-debug/bin/compile.sh
            - chmod +x webhook/builder/bin/env_generator.sh
            - chmod +x src/local-debug/bin/deploy.sh
    pre_build:
        commands:
            - cd src/local-debug
            - ../../webhook/builder/bin/env_generator.sh
    build:
        commands:
            - ./bin/compile.sh
    post_build:
        commands:
            - ./bin/deploy.sh
