version: 0.2

shell: bash
phases:
    install:
        runtime-versions:
            nodejs: 14
        commands:
            - chmod +x webhook/proxy/bin/compile.sh
            - chmod +x webhook/builder/bin/env_generator.sh
            - chmod +x webhook/proxy/bin/deploy.sh
    pre_build:
        commands:
            - cd webhook/proxy
            - ../../webhook/builder/bin/env_generator.sh
    build:
        commands:
            - ./bin/compile.sh
    post_build:
        commands:
            - ./bin/deploy.sh

