AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    GitRepository:
        Type: String
        Description: Git Repositroy for your project
    AppEnvironment:
        Default: "dev"
        Description: "Application environment (dev, prod)"
        Type: String
Resources:
    CodeBuildLocalDebugProject:
        Type: AWS::CodeBuild::Project
        Properties:
            Name: !Sub local-debug-codebuild-project-${AppEnvironment}
            ServiceRole: !GetAtt CodeBuildRole.Arn
            Artifacts:
                Type: no_artifacts
            Environment:
                Type: LINUX_CONTAINER
                Image: aws/codebuild/standard:5.0
                ComputeType: BUILD_GENERAL1_SMALL
            Source:
                Location: !Ref GitRepository
                Type: GITHUB
                BuildSpec: src/local-debug/cloudformation/buildspec.yaml
            TimeoutInMinutes: 15

    CodeBuildRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Action: ['sts:AssumeRole']
                      Effect: Allow
                      Principal:
                          Service: [codebuild.amazonaws.com]
                Version: '2012-10-17'
            Path: /
            Policies:
                - PolicyName: CodeBuildAccess
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Action:
                                - 'logs:*'
                                - 's3:*'
                                - 'cloudformation:*'
                                - 'lambda:*'
                                - 'iam:*'
                                - 'apigateway:*'
                                - 'ssm:*'
                                - 'codedeploy:*'
                                - 'ec2:*'
                                - 'events:*'
                                - 'sqs:*'
                                - 'kinesis:*'
                            Effect: Allow
                            Resource: '*'
